package ssh

import (
	"crypto"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/rsa"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/crypto/ssh"
)

// KeyInfo describes an SSH identity key pair.
type KeyInfo struct {
	Name        string
	Path        string
	PubPath     string
	Fingerprint string
	Type        string
}

// ListKeys scans sshDir for public/private key pairs.
func ListKeys(sshDir string) ([]KeyInfo, error) {
	entries, err := os.ReadDir(sshDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read ssh dir: %w", err)
	}
	var keys []KeyInfo
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".pub") {
			continue
		}
		priv := strings.TrimSuffix(name, ".pub")
		pubPath := filepath.Join(sshDir, name)
		data, err := os.ReadFile(pubPath)
		if err != nil {
			continue
		}
		pub, _, _, _, err := ssh.ParseAuthorizedKey(data)
		if err != nil {
			continue
		}
		keys = append(keys, KeyInfo{
			Name:        priv,
			Path:        filepath.Join(sshDir, priv),
			PubPath:     pubPath,
			Fingerprint: ssh.FingerprintSHA256(pub),
			Type:        pub.Type(),
		})
	}
	return keys, nil
}

// GenerateKey creates a new SSH key pair in sshDir.
func GenerateKey(sshDir, name, keyType string) error {
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return fmt.Errorf("create ssh dir: %w", err)
	}
	privPath := filepath.Join(sshDir, name)
	pubPath := privPath + ".pub"

	var privKey interface{}
	var pubKey crypto.PublicKey
	var err error

	switch strings.ToLower(keyType) {
	case "ed25519":
		var pub ed25519.PublicKey
		pub, privKey, err = ed25519.GenerateKey(rand.Reader)
		pubKey = pub
	case "rsa":
		var rsaPriv *rsa.PrivateKey
		rsaPriv, err = rsa.GenerateKey(rand.Reader, 4096)
		privKey = rsaPriv
		pubKey = &rsaPriv.PublicKey
	default:
		return fmt.Errorf("unsupported key type %s", keyType)
	}
	if err != nil {
		return fmt.Errorf("generate key: %w", err)
	}

	sshPub, err := ssh.NewPublicKey(pubKey)
	if err != nil {
		return fmt.Errorf("create public key: %w", err)
	}

	pemBlock, err := ssh.MarshalPrivateKey(privKey, "generated by ssh-helper")
	if err != nil {
		return fmt.Errorf("marshal private key: %w", err)
	}

	if err := os.WriteFile(privPath, pem.EncodeToMemory(pemBlock), 0o600); err != nil {
		return fmt.Errorf("write private key: %w", err)
	}
	if err := os.WriteFile(pubPath, ssh.MarshalAuthorizedKey(sshPub), 0o644); err != nil {
		return fmt.Errorf("write public key: %w", err)
	}
	return nil
}

// RemoveKey deletes a key pair.
func RemoveKey(privPath string) error {
	_ = os.Remove(privPath + ".pub")
	return os.Remove(privPath)
}

// CopyID copies the public key to the remote host over the provided SSH client.
func CopyID(client *ssh.Client, pubPath string) error {
	data, err := os.ReadFile(pubPath)
	if err != nil {
		return fmt.Errorf("read public key: %w", err)
	}
	session, err := client.NewSession()
	if err != nil {
		return fmt.Errorf("new session: %w", err)
	}
	defer session.Close()

	stdin, err := session.StdinPipe()
	if err != nil {
		return err
	}
	defer stdin.Close()

	if err := session.Start("mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys"); err != nil {
		return fmt.Errorf("start remote command: %w", err)
	}
	if _, err := stdin.Write(data); err != nil {
		return fmt.Errorf("write pubkey: %w", err)
	}
	stdin.Close()
	return session.Wait()
}
